"""UX regression tests after restore/status blocker.

Tester zgłosił:
1. Klik przycisku "Przygotuj dla Claude" nic nie robił, brak feedbacku.
2. Brak visual press state na przycisku.
3. Brak migającego wskaźnika podczas pseudonimizacji.

Te statyczne testy chronią przed regresją kluczowych defensywnych
zachowań w taskpane.js/taskpane.html.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS = (ROOT / "addin" / "taskpane.js").read_text(encoding="utf-8")
HTML = (ROOT / "addin" / "taskpane.html").read_text(encoding="utf-8")


def test_html_has_button_active_press_style():
    """Buttons must show an immediate visual response to click."""
    assert "button:active:not(:disabled)" in HTML, (
        "CSS rule for button:active is required so the user sees the click registered"
    )
    assert "button.is-pressing" in HTML, (
        "CSS class .is-pressing must exist (toggled by bindButton during the click handler)"
    )


def test_html_has_pulsing_busy_dot():
    """Status dot must pulse during long operations so the panel doesn't look frozen."""
    assert ".dot.busy" in HTML
    assert "@keyframes dotPulse" in HTML or "dotPulse" in HTML


def test_bindbutton_toggles_is_pressing_class():
    """bindButton must add and remove .is-pressing around the handler."""
    snippet = JS.split("function bindButton(", 1)[1].split("}\n\n", 1)[0]
    assert 'classList.add("is-pressing")' in snippet
    assert 'classList.remove("is-pressing")' in snippet


def test_bindbutton_logs_clicks_for_diagnostics():
    """console.info on click + error helps the tester capture the cause via F12."""
    snippet = JS.split("function bindButton(", 1)[1].split("}\n\n", 1)[0]
    assert "console.info" in snippet
    assert "console.error" in snippet


def test_main_action_no_longer_silent_on_server_failure():
    """Previously a silent `return` after !ok left the user thinking nothing happened."""
    snippet = JS.split("async function mainAction(", 1)[1].split("\n}\n", 1)[0]
    # New behaviour: surface the failure in both setState and setNotice
    assert "Pseudonimizacja przerwana" in snippet
    assert 'setState("danger"' in snippet


def test_main_action_announces_click_immediately():
    """The handler must update the UI before any slow Office.js await."""
    snippet = JS.split("async function mainAction(", 1)[1].split("\n}\n", 1)[0]
    assert "Klik zarejestrowany" in snippet


def test_setbusy_uses_pulsing_dot():
    """setBusy(true, msg) must put the dot into the .busy (pulsing) state."""
    snippet = JS.split("function setBusy(", 1)[1].split("\n}\n", 1)[0]
    assert 'setState("busy"' in snippet


def test_apipost_distinguishes_network_from_http_errors():
    """A dead backend must produce a clearer message than `TypeError: Failed to fetch`.

    The message is now generated by _csmNetworkErrorMessage() which distinguishes
    between abort/timeout and general network errors.
    """
    # The helper function must exist and contain actionable text.
    assert "_csmNetworkErrorMessage" in JS
    assert "CSM" in JS
    # apiPost must call the helper and log the error.
    snippet = JS.split("async function apiPost(", 1)[1].split("\n}\n", 1)[0]
    assert "_csmNetworkErrorMessage" in snippet
    assert "console.error" in snippet


def test_office_onready_has_8s_watchdog():
    """If Office.onReady never fires, the panel must self-diagnose instead of freezing."""
    assert "Office.onReady nie wystartowało" in JS
    assert "_csmOfficeReady" in JS


def test_early_breadcrumb_shows_script_loaded():
    """Set a visible status before Office.onReady so the tester knows JS at least loaded."""
    assert "Skrypt panelu" in JS and "wczytany" in JS


def test_no_stale_prerelease_version_strings_in_status():
    """Hardcoded legacy prerelease versions must not leak into UI strings."""
    # Allow APP_VERSION constant and version mentions in comments inside templates.
    forbidden = ['"Panel v0.3.0-' + "al" + "pha", "'Panel v0.3.0-" + "al" + "pha"]
    for marker in forbidden:
        assert marker not in JS, f"Stale version string still in taskpane.js: {marker}"


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_"):
            fn()
    print("OK: UX regression tests passed")
