from __future__ import annotations

COMMON_UPPERCASE_STOPWORDS = {
    "RODO", "VAT", "PIT", "CIT", "ZUS", "US", "UE", "SN", "NSA", "WSA",
    "KRS", "NIP", "REGON", "PESEL", "IBAN", "PDF", "DOCX", "HTML", "XML",
    "POSTANOWIENIA", "UMOWA", "STRONA", "STRONY", "KLIENT", "USLUGI", "USŁUGI",
    "PRZEDMIOT", "OGOLNE", "OGÓLNE", "WARUNKI", "SWIADCZENIA", "ŚWIADCZENIA",
    "POUFNE", "POUFNOSCI", "POUFNOŚCI", "KLAUZULA", "KODEKS", "CYWILNY", "CYWILNEGO",
    "ZARZAD", "ZARZĄD", "DORADZTWO", "ZLECENIE", "ZLECENIA",
    "AI", "API", "CRM", "ERP", "SLA", "SEO", "B2B", "B2C", "DPA", "SOW",
    "PKD", "PKWIU", "NBP", "GIODO", "UODO", "KNF", "UOKIK", "MF", "MS", "CEO", "CFO",
}
ROLE_ALIASES = {
    "ZAMAWIAJĄCY", "ZAMAWIAJACY", "WYKONAWCA", "USŁUGODAWCA", "USLUGODAWCA",
    "USŁUGOBIORCA", "USLUGOBIORCA", "KLIENT", "KONTRAHENT", "PARTNER",
    "DOSTAWCA", "ODBIORCA", "SPRZEDAWCA", "SPRZEDAJĄCY", "SPRZEDAJACY",
    "KUPUJĄCY", "KUPUJACY", "KUPUJĄCEGO", "KUPUJACEGO", "KUPUJĄCYCH", "KUPUJACYCH",
    "ZBYWCA", "ZBYWAJĄCY", "ZBYWAJACY", "NABYWCA", "NABYWAJĄCY", "NABYWAJACY",
    "WŁAŚCICIEL", "WLASCICIEL", "WŁAŚCICIELE", "WLASCICIELE",
    "WYNAJMUJĄCY", "WYNAJMUJACY", "NAJEMCA", "DZIERŻAWCA", "DZIERZAWCA",
    "WYDZIERŻAWIAJĄCY", "WYDZIERZAWIAJACY", "POŻYCZKODAWCA", "POZYCZKODAWCA",
    "POŻYCZKOBIORCA", "POZYCZKOBIORCA", "INWESTOR", "DEWELOPER",
    "LICENCJODAWCA", "LICENCJOBIORCA", "ADMINISTRATOR", "PODMIOT", "STRONA", "STRONY",
    # Generic company/entity role labels used as pronouns for a contract party.
    # "Spółka" (= the Company) is routinely introduced by "zwana dalej Spółką" and
    # then used throughout as a party pronoun — it must never be masked.
    "SPÓŁKA", "SPOLKA", "SPÓŁKI", "SPOLKI", "SPÓŁCE", "SPOLCE",
    "SPÓŁKĘ", "SPOLKE", "SPÓŁKĄ", "SPOLKA", "SPÓŁKO", "SPOLKO",
    "SPÓŁEK", "SPOLEK",
}


LEGAL_TITLE_STOP_PHRASES = {
    "PRZEDMIOT UMOWY", "OGÓLNE WARUNKI", "OGOLNE WARUNKI",
    "ŚWIADCZENIA USŁUG", "SWIADCZENIA USLUG", "ŚWIADCZENIE USŁUG", "SWIADCZENIE USLUG",
    "INFORMACJE POUFNE", "KLAUZULA POUFNOŚCI", "KLAUZULA POUFNOSCI",
    "KODEKS CYWILNY", "KODEKSU CYWILNEGO", "KODEKS POSTĘPOWANIA CYWILNEGO", "KODEKSU POSTEPOWANIA CYWILNEGO",
    "ZARZĄD KLIENTA", "ZARZAD KLIENTA", "STRONA NARUSZAJĄCA", "STRONA NARUSZAJACA",
    "STRONIE KARĘ UMOWNĄ", "STRONIE KARE UMOWNA", "KARA UMOWNA", "KARY UMOWNE",
    "POSTANOWIENIA KOŃCOWE", "POSTANOWIENIA KONCOWE", "POSTANOWIENIA OGÓLNE", "POSTANOWIENIA OGOLNE",
    "ZAŁĄCZNIK", "ZALACZNIK", "ZAŁĄCZNIKI", "ZALACZNIKI",
    "PRZEDMIOT", "UMOWA", "UMOWY", "UMOWIE", "OGÓLNYCH WARUNKÓW", "OGOLNYCH WARUNKOW",
    "OGÓLNYCH WARUNKACH", "OGOLNYCH WARUNKACH", "ŚWIADCZEŃ USŁUG", "SWIADCZEN USLUG",
    "INFORMACJI POUFNYCH", "KLAUZULI POUFNOŚCI", "KLAUZULI POUFNOSCI",
    "ZARZĄDU KLIENTA", "ZARZADU KLIENTA", "RACHUNEK BANKOWY", "BIAŁA LISTA", "BIALA LISTA",
    "PODATNIKÓW VAT", "PODATNIKOW VAT",
}

LEGAL_WORD_STOPLIST = {
    "UMOWA", "UMOWY", "UMOWIE", "UMOWĄ", "UMOWA",
    "WARUNKI", "WARUNKÓW", "WARUNKACH", "OGÓLNE", "OGOLNE",
    "ŚWIADCZENIA", "SWIADCZENIA", "USŁUG", "USLUG", "USŁUGI", "USLUGI",
    "INFORMACJE", "POUFNE", "POUFNOŚCI", "POUFNOSCI", "KLAUZULA",
    "KODEKS", "KODEKSU", "CYWILNY", "CYWILNEGO",
    "PRZEDMIOT", "POSTANOWIENIA", "KOŃCOWE", "KONCOWE",
    "ZARZĄD", "ZARZAD", "KLIENTA", "STRONA", "STRONIE", "STRONY",
    "NARUSZAJĄCA", "NARUSZAJACA", "KARA", "KARĘ", "KARE", "UMOWNA", "UMOWNĄ",
    "DORADZTWO", "ZLECENIE", "ZLECENIA", "ZLECEŃ", "ZLECEN", "DOKUMENT", "DOKUMENTU", "TOŻSAMOŚCI", "TOZSAMOSCI",
    # Document-type words that appear in "zwane dalej Porozumieniem" etc. Must not be
    # registered as confidential aliases — they are document titles, not party names.
    "POROZUMIENIE", "POROZUMIENIA", "POROZUMIENIU", "POROZUMIENIEM", "POROZUMIENIACH",
    "KONTRAKT", "KONTRAKTU", "KONTRAKCIE", "KONTRAKTEM",
    "ANEKS", "ANEKSU", "ANEKSIE", "ANEKSEM",
    "PROTOKÓŁ", "PROTOKOL", "PROTOKOŁU", "PROTOKOLU", "PROTOKOLE", "PROTOKOŁEM", "PROTOKOLEM",
    "OFERTA", "OFERTY", "OFERCIE", "OFERTĄ", "OFERTA",
    "ZAMÓWIENIE", "ZAMOWIENIE", "ZAMÓWIENIA", "ZAMOWIENIA", "ZAMÓWIENIU", "ZAMOWIENIU",
    "REGULAMIN", "REGULAMINU", "REGULAMINIE", "REGULAMINEM",
    "STATUT", "STATUTU", "STATUCIE", "STATUTEM",
}

COMMON_POLISH_FIRST_NAMES = {
    "ADAM", "ADRIAN", "BERNARDETA", "DOMINIK", "AGNIESZKA", "ALAN", "ALEKSANDER", "ALEKSANDRA", "ALICJA", "ANNA", "ANTONI",
    "ANDRZEJ", "ARTUR", "BARTŁOMIEJ", "BARTLOMIEJ", "BARTOSZ", "BEATA", "BOGUSŁAW", "BOGUSLAW", "CEZARY", "DANIEL",
    "DARIUSZ", "DOROTA", "EDYTA", "EWA", "FILIP", "GRZEGORZ", "HANNA", "IRENA", "IRYNA", "IRINA", "JACEK",
    "JAN", "JANUSZ", "JERZY", "JOANNA", "JULIA", "KAMIL", "KAROL", "KATARZYNA", "KRZYSZTOF",
    "LUCJAN", "ŁUKASZ", "LUKASZ", "MAGDALENA", "MAŁGORZATA", "MALGORZATA", "MARCIN", "MAREK", "MARIA",
    "MARIUSZ", "MARTA", "MATEUSZ", "MICHAŁ", "MICHAL", "MONIKA", "NATALIA", "PAWEŁ", "PAWEL",
    "PIOTR", "RAFAŁ", "RAFAL", "ROBERT", "SEBASTIAN", "SŁAWOMIR", "SLAWOMIR", "STELLA", "TOMASZ",
    "WOJCIECH", "ZBIGNIEW", "ZUZANNA", "ANETA", "BARBARA", "KLAUDIA", "KAMILA", "PATRYCJA",
    # Frequent names and foreign/Slavic variants observed in legal deeds/contracts.
    "ANDRZEJ", "LUCJAN", "IRYNA", "IRINA", "IRYNA", "STELLA", "OLENA", "OKSANA",
    "TETIANA", "TATIANA", "NATALIIA", "NATALIA", "OLEKSANDR", "ALEKSANDR", "ALEXANDER",
    "MYKHAILO", "MIKHAIL", "SERHII", "SERGEI", "YURI", "JURIJ", "DMYTRO", "VOLODYMYR",
}

# Legacy regression: contract role labels in plural/inflected forms should not be
# anonymized as confidential aliases after "zwanymi dalej".
ROLE_ALIASES.update({
    "SPRZEDAJĄCEGO", "SPRZEDAJACEGO", "SPRZEDAJĄCEMU", "SPRZEDAJACEMU",
    "SPRZEDAJĄCYM", "SPRZEDAJACYM", "SPRZEDAJĄCYMI", "SPRZEDAJACYMI",
    "SPRZEDAJĄCYCH", "SPRZEDAJACYCH", "SPRZEDAWCY", "SPRZEDAWCĄ", "SPRZEDAWCA",
    "KUPUJĄCEMU", "KUPUJACEMU", "KUPUJĄCYM", "KUPUJACYM",
    "KUPUJĄCYMI", "KUPUJACYMI", "NABYWCĄ", "NABYWCA", "NABYWCY",
    "ZBYWCĄ", "ZBYWCA", "ZBYWCY", "WŁAŚCICIELA", "WLASCICIELA",
    "WŁAŚCICIELEM", "WLASCICIELEM", "WŁAŚCICIELAMI", "WLASCICIELAMI",
    "KLIENTA", "KLIENTEM", "KLIENTAMI", "STRONAMI", "STRONĘ", "STRONE", "STRONĄ", "STRONA",
})

# Additional frequent names and foreign/Slavic variants observed in legal deeds/contracts.
COMMON_POLISH_FIRST_NAMES.update({
    "WIKTOR", "WIKTORIA", "STELA", "IRBIS", "OLEKSANDRA", "ALEXANDRA",
    "YULIIA", "YULIA", "IHOR", "IGOR", "VITALII", "VITALIY", "VITALIJ",
})

# Foreign given names frequently seen in cross-border B2B contracts. This keeps
# the default detector deterministic while improving recall for representatives
# such as "François Dupont" or "Hans Müller" without enabling NLP.
COMMON_POLISH_FIRST_NAMES.update({
    "FRANÇOIS", "FRANCOIS", "JEAN", "JEAN-PIERRE", "JEAN-LUC", "PIERRE",
    "HANS", "HEINRICH", "THOMAS", "MICHAEL", "JOHN", "JAMES", "ROBERT",
    "DAVID", "PETER", "PAUL", "MARCO", "MARIO", "LUCA", "LUIS", "CARLOS",
    "MIGUEL", "JOSÉ", "JOSE", "ANTONIO", "MARTIN", "ANDREAS", "JAN",
})

# Common Polish first names that appear as ordinary words when used as surnames
# (e.g. Renata Mucha, Patryk Kowalski, Iwona Teresa). These must be recognised
# as given names so that the full name is correctly detected as PERSON.
COMMON_POLISH_FIRST_NAMES.update({
    "RENATA", "PATRYK", "IWONA", "TERESA", "HENRYK", "CELINA", "WALDEMAR",
    "TADEUSZ", "STANISŁAW", "STANISLAW", "RYSZARD", "MIROSŁAW", "MIROSLAW",
    "WŁADYSŁAW", "WLADYSLAW", "KRYSTYNA", "ELŻBIETA", "ELZBIETA", "HALINA",
    "GRAŻYNA", "GRAZYNA", "BOŻENA", "BOZENA", "WIESŁAW", "WIESLAW",
    "ZENON", "LECH", "MAREK", "ZYGMUNT", "ROMAN", "LEON", "ARNOLD",
})


def deaccent_role(value: str) -> str:
    return value.upper().replace("Ą", "A").replace("Ł", "L").replace("Ś", "S").replace("Ó", "O").replace("Ę", "E").replace("Ź", "Z").replace("Ż", "Z").replace("Ć", "C").replace("Ń", "N")
# Inflected contractual role aliases used in party definitions. They must be
# treated as legal labels, not as confidential company/person aliases.
ROLE_ALIASES.update({
    "SPRZEDAJĄCA", "SPRZEDAJACA", "SPRZEDAJĄCEGO", "SPRZEDAJACEGO",
    "SPRZEDAJĄCEMU", "SPRZEDAJACEMU", "SPRZEDAJĄCYM", "SPRZEDAJACYM",
    "SPRZEDAJĄCYCH", "SPRZEDAJACYCH", "SPRZEDAJĄCYMI", "SPRZEDAJACYMI",
    "SPRZEDAJĄCĄ", "SPRZEDAJACA", "SPRZEDAWCY", "SPRZEDAWCĘ", "SPRZEDAWCE",
    "SPRZEDAWCĄ", "SPRZEDAWCA", "SPRZEDAWCOM", "SPRZEDAWCAMI",
    "KUPUJĄCA", "KUPUJACA", "KUPUJĄCEGO", "KUPUJACEGO", "KUPUJĄCEMU", "KUPUJACEMU",
    "KUPUJĄCYM", "KUPUJACYM", "KUPUJĄCYCH", "KUPUJACYCH", "KUPUJĄCYMI", "KUPUJACYMI",
    "KUPUJĄCĄ", "KUPUJACA", "KUPUJĄCE", "KUPUJACE",
    "NABYWCY", "NABYWCĄ", "NABYWCA", "NABYWCĘ", "NABYWCE", "NABYWCÓW", "NABYWCOW",
    "NABYWCOM", "NABYWCAMI", "NABYWAJĄCY", "NABYWAJACY", "NABYWAJĄCYMI", "NABYWAJACYMI",
    "ZBYWCY", "ZBYWCĄ", "ZBYWCA", "ZBYWCĘ", "ZBYWCE", "ZBYWCÓW", "ZBYWCOW",
    "ZBYWCOM", "ZBYWCAMI", "ZBYWAJĄCYMI", "ZBYWAJACYMI",
    "WŁAŚCICIELA", "WLASCICIELA", "WŁAŚCICIELI", "WLASCICIELI", "WŁAŚCICIELEM", "WLASCICIELEM",
    "WŁAŚCICIELOM", "WLASCICIELOM", "WŁAŚCICIELAMI", "WLASCICIELAMI",
    "WYNAJMUJĄCEGO", "WYNAJMUJACEGO", "WYNAJMUJĄCEMU", "WYNAJMUJACEMU", "WYNAJMUJĄCYM", "WYNAJMUJACYM",
    "NAJEMCĘ", "NAJEMCE", "NAJEMCĄ", "NAJEMCA", "NAJEMCÓW", "NAJEMCOW",
    "DZIERŻAWCĘ", "DZIERZAWCE", "DZIERŻAWCĄ", "DZIERZAWCA", "DZIERŻAWCY", "DZIERZAWCY",
})

LEGAL_WORD_STOPLIST.update({deaccent_role(x) for x in ROLE_ALIASES})


# v0.2.8: dodatkowe stoplisty prawno-biznesowe i odmiany najczęstszych tytułów,
# inspirowane podejściem allowlist/stoplist z narzędzi scrubadub/Presidio.
COMMON_UPPERCASE_STOPWORDS.update({
    "BHP", "OC", "AC", "PPK", "PPE", "GUS", "PFR", "PFRON", "NFZ", "PKO", "PKP", "PKN",
    "PCC", "VATUE", "JPK", "RCP", "HR", "IT", "IP", "IPR", "DPIA", "DPI", "MFA", "2FA",
    "UKE", "URE", "SANEPID", "GIIF", "GIODO", "UODO", "UOKIK", "KNF", "NSA", "WSA", "SA", "SO", "SR",
    "UOP", "B2B", "B2C", "B2G", "SLA", "SOW", "NDA", "DPA", "MSA", "MOU", "API", "SDK", "CRM", "ERP", "CMS", "WMS",
    "SQL", "XML", "JSON", "CSV", "PDF", "DOC", "DOCX", "XLS", "XLSX", "PPT", "PPTX", "OCR", "AI", "ML", "LLM",
})

LEGAL_TITLE_STOP_PHRASES.update({
    "PRZEDMIOTEM UMOWY", "PRZEDMIOTU UMOWY", "PRZEDMIOTOWI UMOWY", "PRZEDMIOCIE UMOWY",
    "OGÓLNYMI WARUNKAMI", "OGOLNYMI WARUNKAMI", "OGÓLNYCH WARUNKÓW", "OGOLNYCH WARUNKOW",
    "OGÓLNYM WARUNKOM", "OGOLNYM WARUNKOM", "OGÓLNYCH WARUNKACH", "OGOLNYCH WARUNKACH",
    "ŚWIADCZENIEM USŁUG", "SWIADCZENIEM USLUG", "ŚWIADCZENIU USŁUG", "SWIADCZENIU USLUG",
    "ŚWIADCZEŃ USŁUG", "SWIADCZEN USLUG", "ŚWIADCZENIAMI USŁUG", "SWIADCZENIAMI USLUG",
    "INFORMACJAMI POUFNYMI", "INFORMACJOM POUFNYM", "INFORMACJACH POUFNYCH",
    "KLAUZULĄ POUFNOŚCI", "KLAUZULA POUFNOSCI", "KLAUZULĄ POUFNOSCI", "KLAUZULI POUFNOŚCI", "KLAUZULI POUFNOSCI",
    "KODEKSEM CYWILNYM", "KODEKSIE CYWILNYM", "KODEKSOWI CYWILNEMU",
    "ZARZĄDEM KLIENTA", "ZARZADEM KLIENTA", "ZARZĄDOWI KLIENTA", "ZARZADOWI KLIENTA", "ZARZĄDZIE KLIENTA", "ZARZADZIE KLIENTA",
    "BIAŁEJ LIŚCIE PODATNIKÓW VAT", "BIALEJ LISCIE PODATNIKOW VAT", "BIAŁĄ LISTĄ PODATNIKÓW VAT", "BIALA LISTA PODATNIKOW VAT",
    "RACHUNKU BANKOWEGO", "RACHUNKIEM BANKOWYM", "RACHUNKOWI BANKOWEMU", "RACHUNKU KLIENTA", "RACHUNEK KLIENTA",
})

LEGAL_WORD_STOPLIST.update({
    "PRZEDMIOTEM", "PRZEDMIOTU", "PRZEDMIOTOWI", "PRZEDMIOCIE",
    "OGÓLNYMI", "OGOLNYMI", "OGÓLNYM", "OGOLNYM", "WARUNKAMI", "WARUNKOM",
    "ŚWIADCZENIEM", "SWIADCZENIEM", "ŚWIADCZENIU", "SWIADCZENIU", "ŚWIADCZEŃ", "SWIADCZEN", "ŚWIADCZENIAMI", "SWIADCZENIAMI",
    "INFORMACJAMI", "INFORMACJOM", "INFORMACJACH", "POUFNYMI", "POUFNYM", "POUFNYCH",
    "KLAUZULĄ", "KLAUZULA", "KLAUZULI", "KODEKSEM", "KODEKSIE", "KODEKSOWI",
    "ZARZĄDEM", "ZARZADEM", "ZARZĄDOWI", "ZARZADOWI", "ZARZĄDZIE", "ZARZADZIE",
    "RACHUNEK", "RACHUNKU", "RACHUNKIEM", "BANKOWY", "BANKOWEGO", "BANKOWYM", "BIAŁA", "BIALA", "BIAŁEJ", "BIALEJ", "LISTA", "LIŚCIE", "LISCIE", "PODATNIKÓW", "PODATNIKOW",
})
