param(
    [Parameter(Mandatory=$true)]
    [string]$ApiBaseUrl,

    [Parameter(Mandatory=$true)]
    [string]$ApiToken,

    [string]$InstallDir = "",
    [string]$OutputFile = ""
)

$ErrorActionPreference = "Stop"

if (-not $InstallDir) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $InstallDir = if ((Split-Path -Leaf $scriptDir) -ieq "tools") { Split-Path -Parent $scriptDir } else { $scriptDir }
}

if (-not $OutputFile) {
    $OutputFile = Join-Path $InstallDir "addin\csm-token.js"
}

function Normalize-BaseUrl([string]$Value) {
    $v = ($Value -as [string]).Trim()
    if (-not $v) { throw "ApiBaseUrl is required." }
    return $v.TrimEnd("/")
}

$apiBase = Normalize-BaseUrl $ApiBaseUrl
$token = ($ApiToken -as [string]).Trim()
if (-not $token) { throw "ApiToken is required." }

$dir = Split-Path -Parent $OutputFile
if ($dir -and -not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

$apiBaseJson = $apiBase | ConvertTo-Json -Compress
$tokenJson = $token | ConvertTo-Json -Compress
$generatedAtJson = (Get-Date).ToUniversalTime().ToString("o") | ConvertTo-Json -Compress

$content = @"
// Generated by tools\write-vps-config.ps1 during CSM VPS provisioning.
window.CSM_API_BASE = $apiBaseJson;
window.CSM_API_BASE_CANDIDATES = [$apiBaseJson, "http://127.0.0.1:8787", "http://localhost:8787"];
window.CSM_TOKEN = $tokenJson;
window.CSM_TOKEN_GENERATED_AT = $generatedAtJson;
window.CSM_VPS_CONFIGURED_AT = $generatedAtJson;
"@

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputFile, $content, $utf8)
Write-Host "CSM VPS config written: $OutputFile"
